module.exports = {
  PROJECTS_RECEIVED: "PROJECTS_RECEIVED",
  PROECT_RECEIVED: "PROJECT_RECEIVED",
  PROJECT_REMOVED: "PROJECT_REMOVED",
  STEP_REMOVED: "STEP_REMOVED",
  STEPS_RECEIVED: "STEPS_RECEIVED"
}
